// Packs Galmuri BDF bitmap fonts (SIL OFL 1.1) into a compact JS module used by the
// game's own pixel-perfect text renderer. Run: node build-font.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const dist = path.join(here, 'tmp', 'package', 'dist');
if (!fs.existsSync(path.join(dist, 'Galmuri11.bdf'))) {
  console.error('갈무리 글꼴 원본(BDF)이 없습니다. 먼저 `npm run fetch-font`(node fetch-font.mjs)를 실행하세요.');
  process.exit(1);
}

function parseBDF(file) {
  const lines = fs.readFileSync(file, 'latin1').split(/\r?\n/);
  const font = { ascent: 0, descent: 0, glyphs: new Map() };
  for (let i = 0; i < lines.length; i++) {
    const l = lines[i];
    if (l.startsWith('FONT_ASCENT ')) font.ascent = +l.split(' ')[1];
    else if (l.startsWith('FONT_DESCENT ')) font.descent = +l.split(' ')[1];
    else if (l.startsWith('STARTCHAR')) {
      let enc = -1, dw = 0, bbx = [0, 0, 0, 0];
      const rows = [];
      i++;
      while (i < lines.length && !lines[i].startsWith('ENDCHAR')) {
        const t = lines[i];
        if (t.startsWith('ENCODING ')) enc = +t.split(/\s+/)[1];
        else if (t.startsWith('DWIDTH ')) dw = +t.split(/\s+/)[1];
        else if (t.startsWith('BBX ')) bbx = t.split(/\s+/).slice(1).map(Number);
        else if (t === 'BITMAP') {
          i++;
          while (i < lines.length && !lines[i].startsWith('ENDCHAR')) { rows.push(lines[i].trim()); i++; }
          break;
        }
        i++;
      }
      if (enc >= 0) font.glyphs.set(enc, { dw, bbx, rows });
    }
  }
  return font;
}

const FULL_RANGES = [
  [0x20, 0x7e], [0xa0, 0xff], [0x2010, 0x2027], [0x2030, 0x203b], [0x2190, 0x2199],
  [0x2500, 0x257f], [0x25a0, 0x25ff], [0x2600, 0x266f], [0x2700, 0x27bf], [0x3000, 0x303f],
  [0x3131, 0x318e], [0xac00, 0xd7a3], [0xff01, 0xff5e]
];

function collectUsedChars() {
  const set = new Set();
  const walk = (dir) => {
    if (!fs.existsSync(dir)) return;
    for (const f of fs.readdirSync(dir)) {
      const p = path.join(dir, f);
      const st = fs.statSync(p);
      if (st.isDirectory()) walk(p);
      else if (f.endsWith('.js') && f !== 'fontdata.js') {
        for (const ch of fs.readFileSync(p, 'utf8')) set.add(ch.codePointAt(0));
      }
    }
  };
  walk(path.join(root, 'js'));
  for (let c = 0x20; c <= 0x7e; c++) set.add(c);
  return set;
}

function pack(font, cps, name) {
  const list = [...cps].filter((c) => font.glyphs.has(c)).sort((a, b) => a - b);
  const ranges = [];
  for (const c of list) {
    const last = ranges[ranges.length - 1];
    if (last && last[0] + last[1] === c) last[1]++;
    else ranges.push([c, 1]);
  }
  const meta = new Uint8Array(list.length * 5);
  const bits = [];
  let acc = 0, nbits = 0;
  const pushBit = (b) => {
    acc = (acc << 1) | b; nbits++;
    if (nbits === 8) { bits.push(acc); acc = 0; nbits = 0; }
  };
  list.forEach((c, gi) => {
    const g = font.glyphs.get(c);
    const [w, h, xo, yo] = g.bbx;
    meta[gi * 5] = g.dw; meta[gi * 5 + 1] = w; meta[gi * 5 + 2] = h;
    meta[gi * 5 + 3] = xo + 16; meta[gi * 5 + 4] = yo + 16;
    for (let y = 0; y < h; y++) {
      const row = g.rows[y] || '';
      const v = BigInt('0x' + (row || '0'));
      const totalBits = row.length * 4;
      for (let x = 0; x < w; x++) {
        const bit = (v >> BigInt(totalBits - 1 - x)) & 1n;
        pushBit(Number(bit));
      }
    }
  });
  if (nbits > 0) bits.push(acc << (8 - nbits));
  let missingHangul = 0;
  for (let c = 0xac00; c <= 0xd7a3; c++) if (cps.has(c) && !font.glyphs.has(c)) missingHangul++;
  console.log(`${name}: ${list.length} glyphs, ${bits.length} bitmap bytes, missing Hangul in request: ${missingHangul}`);
  return {
    ascent: font.ascent, descent: font.descent,
    ranges, meta: Buffer.from(meta).toString('base64'), bits: Buffer.from(Uint8Array.from(bits)).toString('base64')
  };
}

const full = new Set();
for (const [a, b] of FULL_RANGES) for (let c = a; c <= b; c++) full.add(c);
const used = collectUsedChars();
const largeSet = new Set([...used]);
for (const c of [0x2605, 0x2606, 0x2665, 0x25b6, 0x25bc, 0x00b7, 0x2026]) largeSet.add(c);

const out = {
  body: pack(parseBDF(path.join(dist, 'Galmuri11.bdf')), full, 'body (Galmuri11)'),
  bold: pack(parseBDF(path.join(dist, 'Galmuri11-Bold.bdf')), full, 'bold (Galmuri11-Bold)'),
  small: pack(parseBDF(path.join(dist, 'Galmuri9.bdf')), full, 'small (Galmuri9)'),
  large: pack(parseBDF(path.join(dist, 'Galmuri14.bdf')), largeSet, 'large (Galmuri14)')
};

const header = '// Generated by tools/build-font.mjs — bitmap glyphs derived from the Galmuri fonts\n' +
  '// (c) Lee Minseo, SIL Open Font License 1.1 (see fonts/Galmuri-OFL.txt). Do not edit by hand.\n';
fs.mkdirSync(path.join(root, 'js', 'core'), { recursive: true });
fs.writeFileSync(path.join(root, 'js', 'core', 'fontdata.js'), header + 'window.RS = window.RS || {};\nRS.FONT_DATA = ' + JSON.stringify(out) + ';\n');
fs.mkdirSync(path.join(root, 'fonts'), { recursive: true });
fs.copyFileSync(path.join(dist, 'LICENSE.txt'), path.join(root, 'fonts', 'Galmuri-OFL.txt'));
const size = fs.statSync(path.join(root, 'js', 'core', 'fontdata.js')).size;
console.log('wrote js/core/fontdata.js', (size / 1024).toFixed(1), 'KB');
